[project]
name = "portfolio_opt"
version = "0.1"
dependencies = ["pandas", "yfinance","numpy","matplotlib", "flask", "flask-cors", "PyPortfolioOpt", "scikit-learn"]

[project.optional-dependencies]
dev = [
    "black",
    "pylint",
    "PyQt6"
]
